out = open("OfflineScanModal.jsx", "w", encoding="utf-8")
L = out.write

L('import React, { useState, useRef, useEffect, useCallback } from "react";\n')
L('import { analyzeForm, generateReferencePdf, downloadPdf, base64ToBlobUrl, getConfStyle, checkScanServiceHealth } from "../services/scanService";\n\n')

L('const STEPS = ["upload","processing","review","voice","pdf"];\n')
L('const STEP_LABELS = ["1 Upload","2 Process","3 Review","4 Voice","5 PDF"];\n')
L('const PROC_STAGES = [\n')
L('  {id:"upload",label:"Uploading document",pct:10},\n')
L('  {id:"ocr",label:"Running AI OCR (EasyOCR)",pct:35},\n')
L('  {id:"layoutlmv3",label:"LayoutLMv3 Analysis",pct:70},\n')
L('  {id:"autofill",label:"Cross-referencing profile",pct:90},\n')
L('  {id:"done",label:"Complete!",pct:100},\n')
L('];\n\n')

L('export default function OfflineScanModal({onClose,userProfile={}}){\n')
L('  const [step,setStep]=useState("upload");\n')
L('  const [file,setFile]=useState(null);\n')
L('  const [preview,setPreview]=useState(null);\n')
L('  const [procStage,setProcStage]=useState("");\n')
L('  const [procPct,setProcPct]=useState(0);\n')
L('  const [analysis,setAnalysis]=useState(null);\n')
L('  const [error,setError]=useState("");\n')
L('  const [pdfB64,setPdfB64]=useState(null);\n')
L('  const [pdfUrl,setPdfUrl]=useState(null);\n')
L('  const [voiceIdx,setVoiceIdx]=useState(0);\n')
L('  const [voiceActive,setVoiceActive]=useState(false);\n')
L('  const [svcStatus,setSvcStatus]=useState(null);\n')
L('  const [generating,setGenerating]=useState(false);\n')
L('  const fileRef=useRef(null);\n')
L('  const recogRef=useRef(null);\n\n')

L('  useEffect(()=>{checkScanServiceHealth().then(setSvcStatus);},[]);\n')
L('  useEffect(()=>()=>{recogRef.current?.stop();window.speechSynthesis?.cancel();},[]);\n\n')

L('  function pickFile(f){\n')
L('    if(!f)return;\n')
L('    const ok=["application/pdf","image/jpeg","image/png","image/jpg"].includes(f.type)||/\\.(pdf|jpg|jpeg|png)$/i.test(f.name);\n')
L('    if(!ok){setError("Please upload PDF, JPG or PNG.");return;}\n')
L('    setError("");setFile(f);\n')
L('    if(f.type.startsWith("image/")){const r=new FileReader();r.onload=e=>setPreview(e.target.result);r.readAsDataURL(f);}else setPreview(null);\n')
L('  }\n\n')

L('  async function startAnalysis(){\n')
L('    if(!file)return;\n')
L('    setStep("processing");setError("");setProcPct(0);\n')
L('    try{\n')
L('      const result=await analyzeForm(file,userProfile,"en",(stage,pct)=>{setProcStage(stage);setProcPct(pct);});\n')
L('      setAnalysis(result);setStep("review");\n')
L('    }catch(e){setError(e.message);setStep("upload");}\n')
L('  }\n\n')

L('  async function handleGeneratePdf(){\n')
L('    setGenerating(true);setError("");\n')
L('    try{\n')
L('      const b64=await generateReferencePdf(analysis,userProfile);\n')
L('      setPdfB64(b64);setPdfUrl(base64ToBlobUrl(b64));setStep("pdf");\n')
L('    }catch(e){setError(e.message);}finally{setGenerating(false);}\n')
L('  }\n\n')

L('  const speakField=useCallback((field)=>{\n')
L('    if(!window.speechSynthesis||!field)return;\n')
L('    // Small delay to ensure browser handles the sequence\n')
L('    setTimeout(()=>{\n')
L('      window.speechSynthesis.cancel();\n')
L('      const txt=`Field: ${field.label}. ${field.value?"Current value: "+field.value+".":"This field is currently empty."} ${field.explanation||""}`;\n')
L('      const u=new SpeechSynthesisUtterance(txt);\n')
L('      u.rate=0.85;u.pitch=1.0;\n')
L('      u.onstart = () => console.log("Speech started");\n')
L('      u.onerror = (e) => console.error("Speech error", e);\n')
L('      window.speechSynthesis.speak(u);\n')
L('    }, 100);\n')
L('  },[]);\n\n')

L('  function voiceNav(dir,fields){\n')
L('    const next=Math.max(0,Math.min(fields.length-1,voiceIdx+dir));\n')
L('    setVoiceIdx(next);\n')
L('    speakField(fields[next]);\n')
L('  }\n\n')

L('  function toggleSTT(fields,curIdx){\n')
L('    if(voiceActive){recogRef.current?.stop();setVoiceActive(false);return;}\n')
L('    const SR=window.SpeechRecognition||window.webkitSpeechRecognition;\n')
L('    if(!SR){setError("Speech recognition not supported.");return;}\n')
L('    const r=new SR();\n')
L('    r.continuous=false;r.lang="en-IN";\n')
L('    r.onresult=e=>{\n')
L('      const t=e.results[0][0].transcript.toLowerCase().trim();\n')
L('      if(t.includes("next"))voiceNav(1,fields);\n')
L('      else if(t.includes("previous")||t.includes("back"))voiceNav(-1,fields);\n')
L('      else if(t.includes("explain"))speakField(fields[curIdx]);\n')
L('      else if(t.includes("skip"))voiceNav(1,fields);\n')
L('      else if(t.includes("close"))onClose();\n')
L('      setVoiceActive(false);\n')
L('    };\n')
L('    r.onerror=()=>setVoiceActive(false);\n')
L('    r.onend=()=>setVoiceActive(false);\n')
L('    recogRef.current=r;r.start();setVoiceActive(true);\n')
L('  }\n\n')

L('  function onDrop(e){e.preventDefault();pickFile(e.dataTransfer.files[0]);}\n\n')

L('  const CC={\n')
L('    green:{border:"border-emerald-400",bg:"bg-emerald-50",badge:"bg-emerald-100 text-emerald-800",dot:"bg-emerald-500"},\n')
L('    yellow:{border:"border-amber-400",bg:"bg-amber-50",badge:"bg-amber-100 text-amber-800",dot:"bg-amber-400"},\n')
L('    red:{border:"border-red-400",bg:"bg-red-50",badge:"bg-red-100 text-red-800",dot:"bg-red-500"},\n')
L('  };\n')
L('  function cs(level){return CC[level]||CC.yellow;}\n\n')

L('  const fields=analysis?.fields||[];\n')
L('  const curField=fields[voiceIdx];\n\n')

L('  return(\n')
L('    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4" onClick={e=>e.target===e.currentTarget&&onClose()}>\n')
L('      <div className="relative w-full max-w-3xl max-h-[92vh] flex flex-col bg-white rounded-3xl shadow-2xl border border-slate-200 overflow-hidden">\n')

L('        <div className="flex items-center justify-between px-6 py-4 bg-gradient-to-r from-indigo-900 to-violet-800 text-white shrink-0">\n')
L('          <div>\n')
L('            <div className="text-xs font-bold uppercase tracking-widest text-indigo-300 mb-0.5">Sahayak AI</div>\n')
L('            <h2 className="text-lg font-extrabold">Offline Scan &amp; AI Form Assist</h2>\n')
L('            <div className="text-xs text-indigo-200 mt-0.5">LayoutLMv3 · EasyOCR · Voice Guide</div>\n')
L('          </div>\n')
L('          <div className="flex items-center gap-3">\n')
L('            {svcStatus!==null&&<span className={`text-[10px] font-bold px-2 py-1 rounded-full ${svcStatus.ok?"bg-emerald-500":"bg-amber-500"}`}>{svcStatus.ok?"AI READY":"TESSERACT MODE"}</span>}\n')
L('            <button onClick={onClose} className="w-8 h-8 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition-all text-sm">✕</button>\n')
L('          </div>\n')
L('        </div>\n')

L('        <div className="flex gap-1 px-6 pt-3 pb-0 shrink-0">\n')
L('          {STEP_LABELS.map((s,i)=>{\n')
L('            const sKey=STEPS[i];const done=STEPS.indexOf(step)>i;const active=step===sKey;\n')
L('            return(<div key={s} className={`flex-1 text-center text-[10px] font-bold py-1.5 rounded-t-lg border-b-2 transition-all ${active?"border-indigo-600 text-indigo-700 bg-indigo-50":done?"border-emerald-400 text-emerald-600 bg-emerald-50":"border-transparent text-slate-400"}`}>{s}</div>);\n')
L('          })}\n')
L('        </div>\n')

L('        <div className="flex-1 overflow-y-auto p-6">\n')
L('          {error&&<div className="mb-4 rounded-xl bg-red-50 border border-red-200 p-3 text-sm text-red-800 font-medium">{error}</div>}\n\n')

L('          {step==="upload"&&(\n')
L('            <div className="space-y-4">\n')
L('              <div onDragOver={e=>e.preventDefault()} onDrop={onDrop} onClick={()=>fileRef.current?.click()}\n')
L('                className="border-2 border-dashed border-indigo-300 rounded-2xl p-10 text-center cursor-pointer hover:border-indigo-500 hover:bg-indigo-50 transition-all group">\n')
L('                <div className="text-4xl mb-3">{file?"📄":"🗂️"}</div>\n')
L('                {file?(\n')
L('                  <div>\n')
L('                    <div className="font-bold text-slate-800">{file.name}</div>\n')
L('                    <div className="text-sm text-slate-500 mt-1">{(file.size/1024).toFixed(1)} KB</div>\n')
L('                    {preview&&<img src={preview} alt="preview" className="mt-3 max-h-40 mx-auto rounded-xl border"/>}\n')
L('                  </div>\n')
L('                ):(\n')
L('                  <div>\n')
L('                    <div className="font-semibold text-slate-700 group-hover:text-indigo-700">Drop form here or click to browse</div>\n')
L('                    <div className="text-sm text-slate-400 mt-1">PDF · JPG · PNG supported</div>\n')
L('                    <div className="text-xs text-slate-300 mt-1">Works offline · Supports any government form</div>\n')
L('                  </div>\n')
L('                )}\n')
L('                <input ref={fileRef} type="file" accept=".pdf,.jpg,.jpeg,.png" className="hidden" onChange={e=>pickFile(e.target.files[0])}/>\n')
L('              </div>\n')
L('              {file&&(\n')
L('                <button onClick={startAnalysis} className="w-full py-4 rounded-2xl bg-gradient-to-r from-indigo-600 to-violet-600 text-white font-bold text-base shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2">\n')
L('                  <span>🧠</span> Analyze with AI (LayoutLMv3)\n')
L('                </button>\n')
L('              )}\n')
L('            </div>\n')
L('          )}\n\n')

L('          {step==="processing"&&(\n')
L('            <div className="space-y-6 py-4">\n')
L('              <div className="text-center">\n')
L('                <div className="text-5xl mb-4 animate-pulse">🧠</div>\n')
L('                <div className="text-xl font-bold text-slate-800">Processing with AI</div>\n')
L('                <div className="text-sm text-slate-500 mt-1">Using EasyOCR + LayoutLMv3 transformer</div>\n')
L('              </div>\n')
L('              <div className="space-y-3">\n')
L('                {PROC_STAGES.map(stage=>{\n')
L('                  const done=procPct>=stage.pct;const active=procStage===stage.id;\n')
L('                  return(\n')
L('                    <div key={stage.id} className={`flex items-center gap-3 p-3 rounded-xl transition-all ${active?"bg-indigo-50 border border-indigo-200":done?"bg-emerald-50":"bg-slate-50"}`}>\n')
L('                      <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${done?"bg-emerald-500 text-white":active?"bg-indigo-500 text-white animate-pulse":"bg-slate-200 text-slate-400"}`}>{done?"✓":"…"}</div>\n')
L('                      <span className={`text-sm font-medium ${active?"text-indigo-700":done?"text-emerald-700":"text-slate-400"}`}>{stage.label}</span>\n')
L('                    </div>\n')
L('                  );\n')
L('                })}\n')
L('              </div>\n')
L('              <div className="rounded-xl bg-slate-100 overflow-hidden h-3">\n')
L('                <div className="h-full bg-gradient-to-r from-indigo-500 to-violet-500 transition-all duration-700 rounded-full" style={{width:`${procPct}%`}}/>\n')
L('              </div>\n')
L('              <div className="text-center text-sm font-bold text-indigo-700">{procPct}% Complete</div>\n')
L('            </div>\n')
L('          )}\n\n')

L('          {step==="review"&&analysis&&(\n')
L('            <div className="space-y-4">\n')
L('              <div className="flex items-start justify-between">\n')
L('                <div>\n')
L('                  <div className="font-bold text-slate-800 text-sm">{analysis.form_title}</div>\n')
L('                  <div className="text-xs text-slate-500 mt-0.5">Model: <span className="font-semibold text-indigo-600 uppercase">{analysis.model_used}</span> · Confidence: <span className="font-semibold">{Math.round(analysis.overall_confidence*100)}%</span></div>\n')
L('                </div>\n')
L('                <div className="flex gap-2 shrink-0">\n')
L('                  <span className="text-xs bg-emerald-100 text-emerald-800 font-bold px-2 py-1 rounded-full">{analysis.autofill_count} auto</span>\n')
L('                  <span className="text-xs bg-red-100 text-red-800 font-bold px-2 py-1 rounded-full">{analysis.missing_count} missing</span>\n')
L('                </div>\n')
L('              </div>\n')
L('              <div className="space-y-2 max-h-72 overflow-y-auto pr-1">\n')
L('                {fields.map(f=>{\n')
L('                  const c=cs(f.conf_level);\n')
L('                  return(\n')
L('                    <div key={f.field_id} className={`p-3 rounded-xl border-2 ${c.border} ${c.bg}`}>\n')
L('                      <div className="flex items-start justify-between gap-2">\n')
L('                        <div className="flex-1 min-w-0">\n')
L('                          <div className="flex items-center gap-2 flex-wrap">\n')
L('                            <div className={`w-2 h-2 rounded-full shrink-0 ${c.dot}`}/>\n')
L('                            <span className="text-xs font-bold text-slate-600 uppercase tracking-wide">{f.label}</span>\n')
L('                            {f.required&&<span className="text-[9px] font-bold text-red-600">REQUIRED</span>}\n')
L('                            {f.autofilled&&<span className="text-[9px] font-bold text-emerald-700 bg-emerald-100 px-1.5 py-0.5 rounded-full">AUTO-FILLED</span>}\n')
L('                          </div>\n')
L('                          <div className="mt-1 text-sm font-semibold text-slate-800 pl-4">{f.value||<span className="text-slate-300 italic font-normal">Not filled</span>}</div>\n')
L('                          {f.warning&&<div className="mt-1 text-[11px] text-amber-700 pl-4">⚠ {f.warning}</div>}\n')
L('                        </div>\n')
L('                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full shrink-0 ${c.badge}`}>{Math.round(f.confidence*100)}%</span>\n')
L('                      </div>\n')
L('                    </div>\n')
L('                  );\n')
L('                })}\n')
L('              </div>\n')
L('              <div className="flex gap-3">\n')
L('                <button onClick={()=>{setStep("voice");speakField(fields[0]);}} className="flex-1 py-3 rounded-2xl bg-gradient-to-r from-violet-600 to-purple-600 text-white font-bold hover:-translate-y-0.5 transition-all shadow-lg flex items-center justify-center gap-2 text-sm">🎙️ Start Voice Guide</button>\n')
L('                <button onClick={handleGeneratePdf} disabled={generating} className="flex-1 py-3 rounded-2xl bg-gradient-to-r from-indigo-600 to-blue-600 text-white font-bold hover:-translate-y-0.5 transition-all shadow-lg flex items-center justify-center gap-2 text-sm disabled:opacity-60">{generating?"Generating…":"📄 Generate PDF"}</button>\n')
L('              </div>\n')
L('            </div>\n')
L('          )}\n\n')

L('          {step==="voice"&&analysis&&curField&&(\n')
L('            <div className="space-y-5">\n')
L('              <div className="text-center py-2">\n')
L('                <div className="text-4xl mb-2">🎙️</div>\n')
L('                <div className="font-bold text-slate-800 text-lg">Voice-Guided Assistance</div>\n')
L('                <div className="text-xs text-slate-400">Field {voiceIdx+1} of {fields.length}</div>\n')
L('              </div>\n')
L('              <div className={`p-5 rounded-2xl border-2 ${cs(curField.conf_level).border} ${cs(curField.conf_level).bg}`}>\n')
L('                <div className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">{curField.label}</div>\n')
L('                <div className="text-2xl font-extrabold text-slate-800 min-h-8">{curField.value||<span className="text-slate-300">Empty</span>}</div>\n')
L('                <div className="mt-3 text-sm text-slate-600 leading-relaxed">{curField.explanation}</div>\n')
L('              </div>\n')
L('              <div className="flex gap-2 justify-center flex-wrap">\n')
L('                <button onClick={()=>voiceNav(-1,fields)} disabled={voiceIdx===0} className="px-4 py-2 rounded-xl bg-slate-100 text-slate-700 font-semibold text-sm hover:bg-slate-200 disabled:opacity-40">← Prev</button>\n')
L('                <button onClick={()=>speakField(curField)} className="px-4 py-2 rounded-xl bg-indigo-100 text-indigo-700 font-semibold text-sm hover:bg-indigo-200">🔊 Read Again</button>\n')
L('                <button onClick={()=>toggleSTT(fields,voiceIdx)} className={`px-4 py-2 rounded-xl font-semibold text-sm transition-all ${voiceActive?"bg-rose-500 text-white animate-pulse":"bg-violet-100 text-violet-700 hover:bg-violet-200"}`}>{voiceActive?"🔴 Listening…":"🎤 Speak"}</button>\n')
L('                <button onClick={()=>voiceNav(1,fields)} disabled={voiceIdx>=fields.length-1} className="px-4 py-2 rounded-xl bg-slate-100 text-slate-700 font-semibold text-sm hover:bg-slate-200 disabled:opacity-40">Next →</button>\n')
L('              </div>\n')
L('              <div className="text-center text-xs text-slate-400">Commands: "Next" · "Back" · "Explain" · "Close"</div>\n')
L('              <div className="w-full bg-slate-100 rounded-full h-1.5">\n')
L('                <div className="h-full bg-violet-500 rounded-full transition-all" style={{width:`${((voiceIdx+1)/fields.length)*100}%`}}/>\n')
L('              </div>\n')
L('              <button onClick={handleGeneratePdf} disabled={generating} className="w-full py-3 rounded-2xl bg-gradient-to-r from-indigo-600 to-violet-600 text-white font-bold hover:-translate-y-0.5 transition-all shadow-lg text-sm disabled:opacity-60">{generating?"Generating PDF…":"📄 Finish & Generate PDF"}</button>\n')
L('            </div>\n')
L('          )}\n\n')

L('          {step==="pdf"&&pdfUrl&&(\n')
L('            <div className="space-y-4">\n')
L('              <div className="text-center">\n')
L('                <div className="text-4xl mb-2">📄</div>\n')
L('                <div className="font-bold text-slate-800">Reference Copy Ready</div>\n')
L('                <div className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-1.5 mt-2 inline-block">⚠ REFERENCE COPY – VERIFY DETAILS BEFORE SUBMITTING</div>\n')
L('              </div>\n')
L('              <iframe src={pdfUrl} className="w-full h-80 rounded-xl border border-slate-200 shadow-inner" title="Reference PDF"/>\n')
L('              <div className="flex gap-3">\n')
L('                <button onClick={()=>downloadPdf(pdfB64,"sahayak-ref-"+Date.now()+".pdf")} className="flex-1 py-3 rounded-2xl bg-gradient-to-r from-emerald-600 to-teal-600 text-white font-bold hover:-translate-y-0.5 transition-all shadow-lg flex items-center justify-center gap-2 text-sm">⬇️ Download PDF</button>\n')
L('                <button onClick={()=>setStep("review")} className="flex-1 py-3 rounded-2xl bg-slate-100 text-slate-700 font-bold hover:bg-slate-200 transition-all text-sm">← Back to Review</button>\n')
L('              </div>\n')
L('            </div>\n')
L('          )}\n')
L('        </div>\n')
L('      </div>\n')
L('    </div>\n')
L('  );\n')
L('}\n')

out.close()
print("OfflineScanModal.jsx updated successfully")
